spring.application.name=customer-management

server.address=localhost
server.port=9090

server.servlet.context-path=/customer-management
spring.mvc.servlet.path=/api/v1
# http://localhost:9090/customer-management/api/v1/swagger-ui/index.html

spring.mongodb.uri=mongodb://localhost:27017/cmdemo

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

eventTopic=cm-events

spring.threads.virtual.enabled=true